#  For compressing the ScreenRefresher.html for inclusion in the Send-ScreenRefresher function in PEWebServer.ps1

[String]$text = @(Get-Content .\ScreenRefresher.html | Where-Object { $_ -notlike '*console.*' } | Where-Object { $_ -notlike '\\*' }) -join ''
$text = $text.Replace(' = ', '=')
$text = $text.Replace('    ', '')
$text = $text.Replace(') {', '){')
$text = $text.Replace(') => {', ')=>{')
$text = $text.Replace(' {', '{')
$text = $text.Replace(': ', ':')
$text = $text.Replace(' />', '/>')
$text = $text.Replace('if (', 'if(')
$text = $text.Replace(', ', ',')
$text = $text.Replace('data1', 'd')
$text = $text.Replace('data2', 'e')
$text = $text.Replace('image1', 'i')
$text = $text.Replace('image2', 'j')
$text = $text.Replace('image3', 'k')
$text = $text.Replace('newImage', 'l')
$text = $text.Replace('oldImage', 'm')
$text = $text.Replace('response', 'r')
$text = $text.Replace('"time"', '"t"')
$text = $text.Replace('screenTime', 't')
$text = $text.Replace('aController', 'c')
$text = $text.Replace('aPromise', 'p')
$text = $text.Replace('aTimeout', 'u')
$text = $text.Replace('Interval1', 'w')
$text = $text.Replace('Interval2', 'x')
$text = $text.Replace('bcolor', 'a')
$text = $text.Replace('imageCheck', 'f')
$text = $text.Replace('imageFound', 'n')
$text = $text.Replace('imageNotFound', 'o')
$text = $text.Replace('borderColor(', 'b(')
$text | Out-File .\ScreenRefresher-Compressed.html -Encoding ascii